### ISSUE TITLE
Log likelihood for kappa and lambda chains

### ISSUE THREAD

**Issue by sravani9408** [Graylab/IgLM#10]
Hello, 

The log-likelihood calculation for Heavy and Light chains is working great. Thank you for that! On that note, I was wondering if it would also be possible to calculate the log-likelihood values for the Kappa and Lambda chains.

Thanks!

**Comment by jeffreyruffolo** [comment]
Hello, unfortunately it isn't currently possible to calculate separate likelihoods for kappa vs lambda light chains, since we only have conditioning tags for heavy vs light.
