### ISSUE TITLE
Full sequence log likelihood calculation

### ISSUE THREAD

**Issue by px172** [Graylab/IgLM#7]
The example code of the full sequence log-likelihood calculation sets the infill_range but the value is not assigned. 

`log_likelihood = iglm.log_likelihood(
    sequence,
    chain_token,
    species_token,
    infill_range=infill_range,
)`

Is `infill_range=infill_range` can be safely deleted for the full sequence calculation?

**Comment by jeffreyruffolo** [comment]
Hello, thanks for pointing this out! I've removed that line now.
