### ISSUE TITLE
Could you please provide the training data？

### ISSUE THREAD

**Issue by jkwang93** [Graylab/IgLM#8]
Hello authors, it's an excellent work. I would like to use the same dataset to train GPT. I believe that the data in your article can become the standard data in this field in the future. Could you please provide the data used in the article? It can be done through email or Google Cloud Drive, etc. 

If you are worried that the data is too large and inconvenient to upload, it is also great to provide scripts for data processing.

Thank you very much.

**Comment by jeffreyruffolo** [comment]
Hello, sorry for the delay! The data are now available here: https://data.graylab.jhu.edu/OAS95.tar.gz
